"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Repository_1 = require("./types/Repository");
var utils_1 = require("./types/utils");
var book1 = { title: "Преступление и наказание", author: "Ф. М. Достоевский", year: 1866 };
var book2 = { title: "Мастер и Маргарита", author: "М. А. Булгаков", year: 1967 };
var repo = new Repository_1.Repository([book1, book2]);
var newBook = { title: "Война и мир", author: "Л. Н. Толстой", year: 1869 };
repo.add(newBook);
console.log("Все книги:", repo.getAll());
var updatedBook = (0, utils_1.updateBook)(book2, { year: 1968 });
console.log("Обновлённая книга:", updatedBook);
var readonlyBooks = (0, utils_1.getReadonlyBooks)(repo);
console.log("Книги только для чтения:", readonlyBooks);
// readonlyBooks.push({ title: "Новая", author: "Автор", year: 2025 });
